### ISSUE TITLE
Incorrect password

### ISSUE THREAD

**Issue by zs6buj** [madhephaestus/Esp32WifiManager#2]
Thank you for this great project for the ESP32!

Arduino version 1.8.9
I installed your library through the library manager, loaded , built and flashed WiFiManager into an ESP32 Dev Board

When I set up AP: MyAP and pass =  password through the IDE serial monitor, then try to connect to SSID = myAP an my Android tablet I get this:

AP starting myAP

Mac Address: 24:0A:C4:0D:AC:80
SYSTEM_EVENT_AP_START
SYSTEM_EVENT_AP_START
Starting AP:myAP

pass = password

Waiting for client to connect to AP 0
Waiting for client to connect to AP 5001
Waiting for client to connect to AP 10002
Waiting for client to connect to AP 15003
Waiting for client to connect to AP 20004
Waiting for client to connect to AP 25005
Waiting for client to connect to AP 30006
Waiting for client to connect to AP 35007
Waiting for client to connect to AP 40008
Waiting for client to connect to AP 45009
Waiting for client to connect to AP 50010
Waiting for client to connect to AP 55011
Waiting for client to connect to AP 60012
Waiting for client to connect to AP 65013
Waiting for client to connect to AP 70014
Waiting for client to connect to AP 75015
E (624658) event: mismatch or invalid event, id=63
E (624659) event: default event handler failed!
Waiting for client to connect to AP 80016
Waiting for client to connect to AP 85017

and this is the attached screenshot from my Android tablet

![image](https://user-images.githubusercontent.com/12892533/58551058-804a8b00-820f-11e9-8d2d-967ee3164d1c.png)

I tried several times with different AP names and password with the same result.

The latest ESP32 idf is loaded in "hardware" and path added.

**Comment by kbickham** [comment]
Same problem here, trying to use smartphone to setup credentials for a project.

**Comment by programmer131** [comment]
password is Wumpus3742
but it seems this isn't wifi manager as other one for esp8266, only allow to enter credentials from serial, and that even isn't working, when connected to AP, and open 192.168.4.1, it show Hello from ESP8266!

**Comment by madhephaestus** [comment]
the credentials are entered via the serial port. To set the ap mode type in the serial monitor:

AP:MyApName

<then it prompts you for a password, you type it and hit enter in the serial monitor>

that will store the password in the Preferences NVM. 

@programmer131 yes, it does in fact work ;)
