### ISSUE TITLE
How to set new wifi credentials in AP mode

### ISSUE THREAD

**Issue by programmer131** [madhephaestus/Esp32WifiManager#4]
hi! we can send ssid/password from serial, but not getting how to do same from wifi, after I connect to esp32 in AP mode and try to open ESP32 IP, it show hello from ESP8266 message.

**Comment by madhephaestus** [comment]
you type
AP:myNewSsid
then it prompts for a new password
enter the password
ti will store that as the AP ssid and the ap password
